name: 'Acceptance'
on:
  push:
    branches:
      - master

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: piotrkubisa/slack-deployment@master
        with:
          slack_channel: slack-deployment